import image1 from "@/public/assests/explorerliveimg1.svg";
import image2 from "@/public/assests/admin_dp.svg";
import { DataInboxInterface } from "../utils/interface";

const data: DataInboxInterface[] = [
  // {
  //   id: 1,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "call",
  //   status: "Action required",
  //   message: "hello",
  // },
  // {
  //   id: 2,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Bashington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "call",
  //   status: "Accepted",
  //   message: "hello",
  // },
  // {
  //   id: 3,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Bashington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "gift",
  //   status: "Rejected",
  //   message: "hello",
  // },
  // {
  //   id: 4,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image2,
  //   chatImg: "/assests/admin_dp.svg",
  //   type: "admin",
  //   status: "Accepted",
  //   message: "hello",
  // },
  // {
  //   id: 5,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "gift",
  //   status: "Accepted",
  //   message: "hello",
  // },
  // {
  //   id: 6,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "call",
  //   status: "Rejected",
  //   message: "hello",
  // },
  // {
  //   id: 7,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "call",
  //   status: "Action required",
  //   message: "hello",
  // },
  // {
  //   id: 8,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Bashington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "call",
  //   status: "Action required",
  //   message: "hello",
  // },
  // {
  //   id: 9,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "gift",
  //   status: "Accepted",
  //   message: "hello",
  // },
  // {
  //   id: 10,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image2,
  //   chatImg: "/assests/admin_dp.svg",
  //   type: "admin",
  //   status: "Accepted",
  //   message: "hello",
  // },
  // {
  //   id: 11,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "call",
  //   status: "Accepted",
  //   message: "hello",
  // },
  // {
  //   id: 12,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "gift",
  //   status: "Rejected",
  //   message: "hello",
  // },
  // {
  //   id: 13,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Bashington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "call",
  //   status: "Accepted",
  //   message: "hello",
  // },
  // {
  //   id: 14,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "call",
  //   status: "Action required",
  //   message: "hello",
  // },
  // {
  //   id: 15,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "call",
  //   status: "Accepted",
  //   message: "hello",
  // },
  // {
  //   id: 16,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "gift",
  //   status: "Rejected",
  //   message: "hello",
  // },
  // {
  //   id: 17,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "call",
  //   status: "Accepted",
  //   message: "hello",
  // },
  // {
  //   id: 18,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "call",
  //   status: "Accepted",
  //   message: "hello",
  // },
  // {
  //   id: 19,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Bashington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "call",
  //   status: "Action required",
  //   message: "hello",
  // },
  // {
  //   id: 20,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image2,
  //   chatImg: "/assests/admin_dp.svg",
  //   type: "admin",
  //   status: "Accepted",
  //   message: "hello",
  // },
  // {
  //   id: 21,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "call",
  //   status: "Accepted",
  //   message: "hello",
  // },
  // {
  //   id: 22,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "call",
  //   status: "Accepted",
  //   message: "hello",
  // },
  // {
  //   id: 23,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image2,
  //   chatImg: "/assests/admin_dp.svg",
  //   type: "admin",
  //   status: "Rejected",
  //   message: "hello",
  // },
  // {
  //   id: 24,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Bashington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "call",
  //   status: "Accepted",
  //   message: "hello",
  // },
  // {
  //   id: 25,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "gift",
  //   status: "Accepted",
  //   message: "hello",
  // },
  // {
  //   id: 26,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "call",
  //   status: "Accepted",
  //   message: "hello",
  // },
  // {
  //   id: 27,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "call",
  //   status: "Accepted",
  //   message: "hello",
  // },
  // {
  //   id: 28,
  //   name: "Claudia Maudi",
  //   age: 24,
  //   sign: "♒️ Aqurius",
  //   gender: "🚹 Female",
  //   bio: "Several paragraphs of randomly generated text will appear. You can also use this function to specify the number of paragraphs and sentences in each paragraph.",
  //   interests: ["✍🏻 Writing", "🦮 Walking dogs"],
  //   time: "4:23",
  //   location: "Washington Dc",
  //   image: image1,
  //   chatImg: "/assests/explorerliveimg1.svg",
  //   type: "call",
  //   status: "Accepted",
  //   message: "hello",
  // },
];

export default data;
